### ISSUE TITLE
Implement form improvements

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/counter#6]
Use form_title instead of form_name.
Use question_title instead of question_name.

and demonstrate translations of form an question title.

**Comment by lognaturel** [comment]
@hooverlunch I believe you have already designed your forms and deployed the release binary of the counter app, right? If so, I don't think we should change the name of the intent parameters because that would mean your forms wouldn't work any more. If not, we could make this change, release it and then you could deploy from the play store instead. 

@grzesiek2010 is there a particular reason for changing "name" to "title"? It does seem a little more precise but if it's going to be disruptive it doesn't seem worth doing.

**Comment by smoyte** [comment]
These things would require code changes on our side at this point and we'd have to be careful about phasing them in because the APK is now "in the wild". If the app could accept either _title or _name that might be best?

Having translations would be nice too.

**Comment by grzesiek2010** [comment]
> @grzesiek2010 is there a particular reason for changing "name" to "title"? It does seem a little more precise but if it's going to be disruptive it doesn't seem worth doing.

As I remember you or @yanokwa told that it would be better (during one of our meetings two weeks ago?) and I forgot to do that... yes now it might be a bit too late, sorry.

**Comment by lognaturel** [comment]
Ah, well, it would have been a nice idea but now that it's "out in nature", let's leave it as it is! @grzesiek2010 can you please edit the PR to show an example of translations but not change the intent parameter names?

@hooverlunch translations already work in the standard way.

**Comment by grzesiek2010** [comment]
@lognaturel it's ready.

**Comment by smoyte** [comment]
>
> @hooverlunch <https://github.com/hooverlunch> translations already work
> in the standard way.
>

Ah, of course!
